-- AIM: TO CREATE VIEWS AND ASSERTIONS.

-- ------------------------------------------------------------------------------------------------------- --


-- 1) 
-- CREATE A TABLE NAMED BANK WITH THE FOLLOWING ATTRIBUTES
-- - BANKCODE (TO BE SET AS PRIMARY KEY, TYPE= VARCHAR(3))
-- - BANKNAME (SHOULD NOT BENULL)
-- - HEADOFFICE
-- - BRANCHES (INTEGER VALUE GREATER THAN ZERO)
-- POPULATE THE DATABASE.
-- MAKE SURE THAT ALL CONSTRAINTS ARE WORKING PROPERLY.
-- ALL CONSTRAINTS HAVE TO BE SET AFTER CREATING THE TABLE.

CREATE TABLE BANK(BANKCODE VARCHAR(3) PRIMARY KEY, BANKNAME VARCHAR(30) NOT NULL, HEADOFFICE VARCHAR(30), BRANCHES INTEGER);

INSERT INTO BANK VALUES('SBI','STATE BANK INDIA', 'DELHI','50');
INSERT INTO BANK VALUES('FB', 'FEDERAL BANK', 'ERANAKULAM', '40');
INSERT INTO BANK VALUES('SBT', 'STATE BANK TRAVANCORE','KOTTAYAM', '35');
INSERT INTO BANK VALUES('AX', 'AXIS BANK','ERANAKULAM','25');
INSERT INTO BANK VALUES('SIB', 'SOUTH INDIAN BANK','ERANAKULAM','38'); 

SELECT * FROM BANK;

-- ------------------------------------------------------------------------------------------------------- --


-- 2)
-- CREATE A TABLE NAMED BRANCH WITH THE FOLLOWING ATTRIBUTE
-- - BRANCHID (TO BE SET AS PRIMARYKEY)
-- - BRANCHNAME (SET DEFAULT VALUE AS 'NEW DELHI')
-- - BANKID (FOREIGN KEY, REFERENCES TO BANKCODE OF BANK TABLE)

CREATE TABLE BRANCH(BRANCHID VARCHAR(3) PRIMARY KEY, BRANCHNAME VARCHAR(30) DEFAULT 'NEW DELHI' NOT NULL,BANKID VARCHAR(3), FOREIGN KEY(BANKID) REFERENCES BANK(BANKCODE));

INSERT INTO BRANCH VALUES('101', DEFAULT,'SBI');
INSERT INTO BRANCH VALUES('102', DEFAULT,'FB');
INSERT INTO BRANCH VALUES('103', DEFAULT,'SBT');
INSERT INTO BRANCH VALUES('104', DEFAULT,'AX');
INSERT INTO BRANCH VALUES('105', DEFAULT, 'SIB');

SELECT * FROM BRANCH;

-- ------------------------------------------------------------------------------------------------------- --


-- 3)
-- DELETE THE BANK WITH BANKCODE 'SBT' AND MAKE SURE THAT THE CORRESPONDING ENTRIES ARE ALSO DELETED

DELETE FROM BRANCH WHERE BANKID='SBT';

DELETE FROM BANK WHERE BANKCODE='SBT';

INSERT INTO BRANCH VALUES('106', 'KOTTAYAM','SBI');

SELECT * FROM BRANCH;

-- ------------------------------------------------------------------------------------------------------- --


-- 4)
-- DROP THE PRIMARY KEY IN BRANCH USING ALTER COMMAND

ALTER TABLE BRANCH DROP PRIMARY KEY;

-- ------------------------------------------------------------------------------------------------------- --


-- 5)
-- CREATE A VIEW NAMED BANK_HEADOFFICE TO HOLD THE DETAILS OF ALL BANKS WHOSE HEAD OFFICE AT ERNAKULAM

CREATE VIEW BANK_HEADOFFICE AS SELECT BANKCODE, BANKNAME, HEADOFFICE, BRANCHES FROM BANK WHERE HEADOFFICE='ERANAKULAM';

SELECT * FROM BANK_HEADOFFICE;

-- ------------------------------------------------------------------------------------------------------- --


-- 6)
-- CREATE A VIEW BANK_BRANCH YOU HOLD THE DETAILS OF ALL BANKS THAT HAVE BRANCHES AT KOTTAYAM

CREATE VIEW BANK_BRANCH AS SELECT BRANCHID, BRANCHNAME, BANKID FROM BRANCH WHERE BRANCHNAME='KOTTAYAM';

SELECT * FROM BANK_BRANCH;